### ISSUE TITLE
Tactician Pipebomb behavior

### ISSUE THREAD

**Issue by TheronS** [ChaosCoreTeam/HideandSeek#29]
After throwing the pipe bomb, should we immediately switch to the detonator like in duke3d? or just keep switching back to the pipe bomb so they can lay down multiple pipe bombs at a faster rate, and have them manually switch to the detonator when they want to try to explode?

Another idea Justin just suggested, was always having the detonator in the other arm, so you can consecutively throw pipebombs, and active the detonator at any time, this is the path I think we should pursue.

**Comment by JustinHeffron** [comment]
I think we will need to test each style for balance purposes. 

I picture with how fast pace a chase is going to be; throwing a pipe bomb at a running hider isn't going to be very effective unless they can instantly blow it up, so I believe the duel wield pipe bomb and detonator would be the way to go. Of course we don't want people to be able to kill hiders too easy with pipe bombs.

I would like to hear more opinions before I make any changes to the functionality (for the time being).

**Comment by TheronS** [comment]
I think having them dual wield, primary fire throws, and alt fire explodes them is ideal. There also might be a way to draw both sprites on screen without having to mesh them together in the same image. I don't remember exactly how to do this, but I believe it is possible.

**Comment by JustinHeffron** [comment]
Duel wield has been added and functions properly.
