### ISSUE TITLE
Tactician tripmine behavior

### ISSUE THREAD

**Issue by TheronS** [ChaosCoreTeam/HideandSeek#30]
Currently slides everywhere, should be easy enough to fix.

**Comment by JustinHeffron** [comment]
Progress has been made in the most recent pull request. Need to figure out how to set a limit + also a couple of bugs need fixin'. For example, the mine wont spawn if you are facing a wall or standing in front of a floor with a different height, but the cooldown timer still activates.

**Comment by TheronS** [comment]
The behavior has been fixed.
