### ISSUE TITLE
Scouter First Ability: Hookshot

### ISSUE THREAD

**Issue by TheronS** [ChaosCoreTeam/HideandSeek#37]
The ability for the most part is fully implemented, it has inconsistent behavior, sometimes the projectile seems to not show once spawned, and I also noticed that it pulls the actor to where the actor was initially standing....

Maybe make the scouter stand still in one spot and hookshot more instantaneous so it's more viable and intuitive?

**Comment by WChrisK** [comment]
@TheronS I will take a look at this and see what is happening, if you know of any way to trigger it let me know (unless it's just random or unpredictable).

**Comment by TheronS** [comment]
I'm going to comment this as done for now, the behavior seems consistent enough.
